## These two functions work together to first define functions to store and access
## a matrix and its inverse, and then a function to check whether the inverse has been cached
## and - if not - calculate and cache the inverse.

## This function takes a matrix as an input and returns a list of functions to access and set
## the stored values of the matrix and its inverse

makeCacheMatrix <- function(m = matrix()) {
        i <- NULL
        set <- function(y) {
                m <<- y
                i <<- NULL
        }
        get <- function() m
        setinverse <- function(inverse) i <<- inverse
        getinverse <- function() i
        list(set = set, get = get, setinverse = setinverse, getinverse = getinverse)
}


## This function takes as an input the list of functions generated by makeCacheMatrix
## and uses getinverse() to check if a value for the inverse has already been cached.
## If not, it calculates the inverse using solve(), stores it in the cache using 
## setinverse(), and returns the inverse

cacheSolve <- function(mlist, ...) {
        ## Return a matrix that is the inverse of 'm' passed to makeCacheMatrix
        i <- mlist$getinverse()
        if(!is.null(i)) {
                message("getting cached data")
                return(i)
        }
        data <- mlist$get()
        i <- solve(data, ...)
        mlist$setinverse(i)
        i
}
